spring:
  application:
    name: arc-raiders-discord-bot
  main:
    web-application-type: none
  cache:
    type: redis
    redis:
      time-to-live: 120000
  data:
    redis:
      client-type: lettuce
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:-0}
management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_TRACES}
    logging:
      export:
        otlp:
          endpoint: ${OTEL_LOGS}
logging:
  level:
    dev:
      lngnr: DEBUG
discord:
  bot-token: ${DISCORD_BOT_TOKEN}
arc-raiders:
  api:
    url:
      events: https://metaforge.app/api/arc-raiders/events-schedule
