services:
  discord-bot:
    image: ghcr.io/lngnr/discord-bot-arc-raiders
    restart: unless-stopped
    environment:
      OTEL_METRICS: http://grafana:4318/v1/metrics
      OTEL_TRACES: http://grafana:4318/v1/traces
      OTEL_LOGS: http://grafana:4318/v1/logs
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
      grafana:
        condition: service_healthy
    networks:
      - discord-bot-network
  redis:
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - discord-bot-network
  grafana:
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    volumes:
      - "./mounts/grafana:/data"
    ports:
      - "3000:3000"
    networks:
      - discord-bot-network

networks:
  discord-bot-network:
    driver: bridge
